//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebServiceClient.EmployeeManagerReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeManagerReference.EmployeeManagerSoap")]
    public interface EmployeeManagerSoap {
        
        // CODEGEN: Generating message contract since element name SelectAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll", ReplyAction="*")]
        EmployeeWebServiceClient.EmployeeManagerReference.SelectAllResponse SelectAll(EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.SelectAllResponse> SelectAllAsync(EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequest request);
        
        // CODEGEN: Generating message contract since element name SelectByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectByID", ReplyAction="*")]
        EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDResponse SelectByID(EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectByID", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDResponse> SelectByIDAsync(EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequest request);
        
        // CODEGEN: Generating message contract since element name obj from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        EmployeeWebServiceClient.EmployeeManagerReference.InsertResponse Insert(EmployeeWebServiceClient.EmployeeManagerReference.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.InsertResponse> InsertAsync(EmployeeWebServiceClient.EmployeeManagerReference.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name emp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        EmployeeWebServiceClient.EmployeeManagerReference.UpdateResponse Update(EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.UpdateResponse> UpdateAsync(EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        EmployeeWebServiceClient.EmployeeManagerReference.DeleteResponse Delete(EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.DeleteResponse> DeleteAsync(EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequestBody Body;
        
        public SelectAllRequest() {
        }
        
        public SelectAllRequest(EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllRequestBody {
        
        public SelectAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.SelectAllResponseBody Body;
        
        public SelectAllResponse() {
        }
        
        public SelectAllResponse(EmployeeWebServiceClient.EmployeeManagerReference.SelectAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.Employee[] SelectAllResult;
        
        public SelectAllResponseBody() {
        }
        
        public SelectAllResponseBody(EmployeeWebServiceClient.EmployeeManagerReference.Employee[] SelectAllResult) {
            this.SelectAllResult = SelectAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectByID", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequestBody Body;
        
        public SelectByIDRequest() {
        }
        
        public SelectByIDRequest(EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SelectByIDRequestBody() {
        }
        
        public SelectByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDResponseBody Body;
        
        public SelectByIDResponse() {
        }
        
        public SelectByIDResponse(EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.Employee SelectByIDResult;
        
        public SelectByIDResponseBody() {
        }
        
        public SelectByIDResponseBody(EmployeeWebServiceClient.EmployeeManagerReference.Employee SelectByIDResult) {
            this.SelectByIDResult = SelectByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(EmployeeWebServiceClient.EmployeeManagerReference.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.Employee obj;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(EmployeeWebServiceClient.EmployeeManagerReference.Employee obj) {
            this.obj = obj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(EmployeeWebServiceClient.EmployeeManagerReference.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(string InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.Employee emp;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(EmployeeWebServiceClient.EmployeeManagerReference.Employee emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(EmployeeWebServiceClient.EmployeeManagerReference.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebServiceClient.EmployeeManagerReference.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(EmployeeWebServiceClient.EmployeeManagerReference.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(string DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeManagerSoapChannel : EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeManagerSoapClient : System.ServiceModel.ClientBase<EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap>, EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap {
        
        public EmployeeManagerSoapClient() {
        }
        
        public EmployeeManagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeManagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeManagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebServiceClient.EmployeeManagerReference.SelectAllResponse EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.SelectAll(EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequest request) {
            return base.Channel.SelectAll(request);
        }
        
        public EmployeeWebServiceClient.EmployeeManagerReference.Employee[] SelectAll() {
            EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequestBody();
            EmployeeWebServiceClient.EmployeeManagerReference.SelectAllResponse retVal = ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).SelectAll(inValue);
            return retVal.Body.SelectAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.SelectAllResponse> EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.SelectAllAsync(EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequest request) {
            return base.Channel.SelectAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.SelectAllResponse> SelectAllAsync() {
            EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.SelectAllRequestBody();
            return ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).SelectAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDResponse EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.SelectByID(EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequest request) {
            return base.Channel.SelectByID(request);
        }
        
        public EmployeeWebServiceClient.EmployeeManagerReference.Employee SelectByID(int id) {
            EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequestBody();
            inValue.Body.id = id;
            EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDResponse retVal = ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).SelectByID(inValue);
            return retVal.Body.SelectByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDResponse> EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.SelectByIDAsync(EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequest request) {
            return base.Channel.SelectByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDResponse> SelectByIDAsync(int id) {
            EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.SelectByIDRequestBody();
            inValue.Body.id = id;
            return ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).SelectByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebServiceClient.EmployeeManagerReference.InsertResponse EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.Insert(EmployeeWebServiceClient.EmployeeManagerReference.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public string Insert(EmployeeWebServiceClient.EmployeeManagerReference.Employee obj) {
            EmployeeWebServiceClient.EmployeeManagerReference.InsertRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.InsertRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.InsertRequestBody();
            inValue.Body.obj = obj;
            EmployeeWebServiceClient.EmployeeManagerReference.InsertResponse retVal = ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.InsertResponse> EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.InsertAsync(EmployeeWebServiceClient.EmployeeManagerReference.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.InsertResponse> InsertAsync(EmployeeWebServiceClient.EmployeeManagerReference.Employee obj) {
            EmployeeWebServiceClient.EmployeeManagerReference.InsertRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.InsertRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.InsertRequestBody();
            inValue.Body.obj = obj;
            return ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebServiceClient.EmployeeManagerReference.UpdateResponse EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.Update(EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(EmployeeWebServiceClient.EmployeeManagerReference.Employee emp) {
            EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequestBody();
            inValue.Body.emp = emp;
            EmployeeWebServiceClient.EmployeeManagerReference.UpdateResponse retVal = ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.UpdateResponse> EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.UpdateAsync(EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.UpdateResponse> UpdateAsync(EmployeeWebServiceClient.EmployeeManagerReference.Employee emp) {
            EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.UpdateRequestBody();
            inValue.Body.emp = emp;
            return ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebServiceClient.EmployeeManagerReference.DeleteResponse EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.Delete(EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public string Delete(int id) {
            EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequestBody();
            inValue.Body.id = id;
            EmployeeWebServiceClient.EmployeeManagerReference.DeleteResponse retVal = ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.DeleteResponse> EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap.DeleteAsync(EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebServiceClient.EmployeeManagerReference.DeleteResponse> DeleteAsync(int id) {
            EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequest inValue = new EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequest();
            inValue.Body = new EmployeeWebServiceClient.EmployeeManagerReference.DeleteRequestBody();
            inValue.Body.id = id;
            return ((EmployeeWebServiceClient.EmployeeManagerReference.EmployeeManagerSoap)(this)).DeleteAsync(inValue);
        }
    }
}
